# Generated by Django 3.0.6 on 2020-05-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webnotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
