# Generated by Django 3.0.6 on 2020-05-14 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webnotes', '0002_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='status_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webnotes.Status'),
        ),
    ]
