# Generated by Django 3.0.6 on 2020-05-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webnotes', '0004_tools'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yarn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color_lot', models.CharField(max_length=100)),
                ('weight', models.IntegerField(null=True)),
                ('length', models.IntegerField(null=True)),
                ('label', models.FileField(upload_to='upload/')),
                ('source', models.URLField(null=True)),
                ('notes_id', models.ManyToManyField(to='webnotes.Notes')),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.FileField(upload_to='upload/')),
                ('scheme', models.FileField(upload_to='upload/')),
                ('description', models.TextField(max_length=1024)),
                ('source', models.URLField(null=True)),
                ('notes_id', models.ManyToManyField(to='webnotes.Notes')),
            ],
        ),
    ]
