# Generated by Django 3.0.6 on 2020-05-15 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webnotes', '0005_pattern_yarn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pattern',
            old_name='notes_id',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='tools',
            old_name='notes_id',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='yarn',
            old_name='notes_id',
            new_name='notes',
        ),
    ]
