# Generated by Django 3.0.6 on 2020-05-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webnotes', '0006_auto_20200515_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='status_id',
            new_name='status',
        ),
    ]
