# Generated by Django 3.0.6 on 2020-05-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webnotes', '0007_auto_20200515_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='image',
            field=models.FileField(null=True, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='note',
            field=models.TextField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='image',
            field=models.FileField(null=True, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='label',
            field=models.FileField(null=True, upload_to='upload/'),
        ),
    ]
