# Generated by Django 3.0.6 on 2020-05-30 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webnotes', '0009_notes_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Craft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Webnote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('create_date', models.DateTimeField(default='2020-05-30 21:54:43')),
                ('for_who', models.CharField(max_length=100)),
                ('image', models.FileField(null=True, upload_to='upload/')),
                ('note', models.TextField(max_length=512, null=True)),
                ('private_status', models.CharField(default=2, max_length=100)),
                ('craft', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webnotes.Craft', verbose_name='Вид рукоделия')),
                ('status', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webnotes.Status', verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='tools',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='yarn',
            name='notes',
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
        migrations.DeleteModel(
            name='Pattern',
        ),
        migrations.DeleteModel(
            name='Tools',
        ),
        migrations.DeleteModel(
            name='Yarn',
        ),
    ]
