# Generated by Django 3.0.6 on 2020-05-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webnotes', '0012_auto_20200531_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='upload/patterns/image')),
                ('scheme', models.FileField(blank=True, null=True, upload_to='upload/patterns/scheme')),
                ('description', models.TextField(max_length=1024)),
                ('source', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Yarn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color_lot', models.CharField(max_length=100)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('label', models.FileField(blank=True, null=True, upload_to='upload/yarns')),
                ('source', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tool',
            name='webnote',
        ),
        migrations.AddField(
            model_name='webnote',
            name='tool',
            field=models.ManyToManyField(to='webnotes.Tool', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='tool',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='producer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='webnote',
            name='create_date',
            field=models.DateTimeField(default='2020-05-31 20:41:10'),
        ),
        migrations.AlterField(
            model_name='webnote',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webnote',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='upload/webnotes'),
        ),
        migrations.AlterField(
            model_name='webnote',
            name='note',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='webnote',
            name='private_status',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='webnote',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webnote',
            name='pattern',
            field=models.ManyToManyField(to='webnotes.Pattern', verbose_name='Узор'),
        ),
        migrations.AddField(
            model_name='webnote',
            name='yarn',
            field=models.ManyToManyField(to='webnotes.Yarn', verbose_name='Пряжа'),
        ),
    ]
