# Generated by Django 3.0.6 on 2020-06-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webnotes', '0014_auto_20200607_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webnote',
            name='access',
        ),
    ]
