# Generated by Django 3.0.6 on 2020-06-07 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webnotes', '0015_remove_webnote_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='webnote',
            name='access',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webnotes.Access', verbose_name='Доступ другим пользователям'),
        ),
    ]
