# Generated by Django 3.0.6 on 2020-06-08 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webnotes', '0017_auto_20200608_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tool',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='webnote',
            name='pattern',
            field=models.ManyToManyField(blank=True, null=True, to='webnotes.Pattern', verbose_name='Узор'),
        ),
        migrations.AlterField(
            model_name='webnote',
            name='tool',
            field=models.ManyToManyField(blank=True, null=True, to='webnotes.Tool', verbose_name='Инструменты'),
        ),
        migrations.AlterField(
            model_name='webnote',
            name='yarn',
            field=models.ManyToManyField(blank=True, null=True, to='webnotes.Yarn', verbose_name='Пряжа'),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
