# Generated by Django 3.0.6 on 2020-06-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webnotes', '0018_auto_20200608_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webnote',
            name='pattern',
            field=models.ManyToManyField(to='webnotes.Pattern', verbose_name='Узор'),
        ),
        migrations.AlterField(
            model_name='webnote',
            name='tool',
            field=models.ManyToManyField(to='webnotes.Tool', verbose_name='Инструменты'),
        ),
        migrations.AlterField(
            model_name='webnote',
            name='yarn',
            field=models.ManyToManyField(to='webnotes.Yarn', verbose_name='Пряжа'),
        ),
    ]
